/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_DOT = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COLON = 5,
  anon_sym_STAR = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_request = 9,
  anon_sym_response = 10,
  sym_identifier = 11,
  sym_integer = 12,
  sym_source_file = 13,
  sym_type_definition = 14,
  sym_field_definition = 15,
  sym_map_specifier = 16,
  sym_protocol_definition = 17,
  sym_request_block = 18,
  sym_response_block = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_type_definition_repeat1 = 21,
  aux_sym_protocol_definition_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_request] = "request",
  [anon_sym_response] = "response",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym_type_definition] = "type_definition",
  [sym_field_definition] = "field_definition",
  [sym_map_specifier] = "map_specifier",
  [sym_protocol_definition] = "protocol_definition",
  [sym_request_block] = "request_block",
  [sym_response_block] = "response_block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_definition_repeat1] = "type_definition_repeat1",
  [aux_sym_protocol_definition_repeat1] = "protocol_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_request] = anon_sym_request,
  [anon_sym_response] = anon_sym_response,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym_type_definition] = sym_type_definition,
  [sym_field_definition] = sym_field_definition,
  [sym_map_specifier] = sym_map_specifier,
  [sym_protocol_definition] = sym_protocol_definition,
  [sym_request_block] = sym_request_block,
  [sym_response_block] = sym_response_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_definition_repeat1] = aux_sym_type_definition_repeat1,
  [aux_sym_protocol_definition_repeat1] = aux_sym_protocol_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_request] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_response] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_map_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_protocol_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_request_block] = {
    .visible = true,
    .named = true,
  },
  [sym_response_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_protocol_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_is_array = 2,
  field_key = 3,
  field_map_key_type = 4,
  field_name = 5,
  field_tag = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_is_array] = "is_array",
  [field_key] = "key",
  [field_map_key_type] = "map_key_type",
  [field_name] = "name",
  [field_tag] = "tag",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 1},
  [7] = {.index = 12, .length = 4},
  [8] = {.index = 16, .length = 4},
  [9] = {.index = 20, .length = 5},
  [10] = {.index = 25, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_tag, 1},
  [3] =
    {field_body, 3},
    {field_name, 1},
  [5] =
    {field_body, 3},
    {field_name, 0},
    {field_tag, 1},
  [8] =
    {field_name, 0},
    {field_tag, 1},
    {field_type, 3},
  [11] =
    {field_body, 2},
  [12] =
    {field_is_array, 3},
    {field_name, 0},
    {field_tag, 1},
    {field_type, 4},
  [16] =
    {field_map_key_type, 4},
    {field_name, 0},
    {field_tag, 1},
    {field_type, 3},
  [20] =
    {field_is_array, 3},
    {field_map_key_type, 5},
    {field_name, 0},
    {field_tag, 1},
    {field_type, 4},
  [25] =
    {field_key, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 10,
  [25] = 11,
  [26] = 23,
  [27] = 27,
  [28] = 28,
  [29] = 22,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 36,
  [45] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '#', 14,
        '(', 20,
        ')', 21,
        '*', 19,
        '.', 15,
        ':', 18,
        'r', 1,
        '{', 16,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'q') ADVANCE(11);
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(2);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_request);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_response);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 12},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_request] = ACTIONS(1),
    [anon_sym_response] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_type_definition] = STATE(6),
    [sym_protocol_definition] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(14), 1,
      anon_sym_RBRACE,
    ACTIONS(16), 1,
      anon_sym_request,
    ACTIONS(19), 1,
      anon_sym_response,
    STATE(2), 4,
      sym_type_definition,
      sym_request_block,
      sym_response_block,
      aux_sym_protocol_definition_repeat1,
  [22] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(22), 1,
      anon_sym_DOT,
    ACTIONS(24), 1,
      anon_sym_RBRACE,
    ACTIONS(26), 1,
      anon_sym_request,
    ACTIONS(28), 1,
      anon_sym_response,
    STATE(4), 4,
      sym_type_definition,
      sym_request_block,
      sym_response_block,
      aux_sym_protocol_definition_repeat1,
  [44] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(22), 1,
      anon_sym_DOT,
    ACTIONS(26), 1,
      anon_sym_request,
    ACTIONS(28), 1,
      anon_sym_response,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    STATE(2), 4,
      sym_type_definition,
      sym_request_block,
      sym_response_block,
      aux_sym_protocol_definition_repeat1,
  [66] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      anon_sym_DOT,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(5), 3,
      sym_type_definition,
      sym_protocol_definition,
      aux_sym_source_file_repeat1,
  [84] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(5), 3,
      sym_type_definition,
      sym_protocol_definition,
      aux_sym_source_file_repeat1,
  [102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [115] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(52), 1,
      sym_identifier,
    STATE(9), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [142] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(11), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [156] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [170] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [184] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [246] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_map_specifier,
    ACTIONS(73), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [280] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_map_specifier,
    ACTIONS(81), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 4,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_request,
      anon_sym_response,
  [314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(25), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [328] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_field_definition,
      aux_sym_type_definition_repeat1,
  [342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      sym_identifier,
  [388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [396] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
  [419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_identifier,
  [426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
  [440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
  [447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_identifier,
  [454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_COLON,
  [461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_integer,
  [468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_integer,
  [475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
  [482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
  [489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 102,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 128,
  [SMALL_STATE(10)] = 142,
  [SMALL_STATE(11)] = 156,
  [SMALL_STATE(12)] = 170,
  [SMALL_STATE(13)] = 184,
  [SMALL_STATE(14)] = 198,
  [SMALL_STATE(15)] = 208,
  [SMALL_STATE(16)] = 222,
  [SMALL_STATE(17)] = 232,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 260,
  [SMALL_STATE(20)] = 270,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 294,
  [SMALL_STATE(23)] = 304,
  [SMALL_STATE(24)] = 314,
  [SMALL_STATE(25)] = 328,
  [SMALL_STATE(26)] = 342,
  [SMALL_STATE(27)] = 351,
  [SMALL_STATE(28)] = 360,
  [SMALL_STATE(29)] = 369,
  [SMALL_STATE(30)] = 378,
  [SMALL_STATE(31)] = 388,
  [SMALL_STATE(32)] = 396,
  [SMALL_STATE(33)] = 404,
  [SMALL_STATE(34)] = 412,
  [SMALL_STATE(35)] = 419,
  [SMALL_STATE(36)] = 426,
  [SMALL_STATE(37)] = 433,
  [SMALL_STATE(38)] = 440,
  [SMALL_STATE(39)] = 447,
  [SMALL_STATE(40)] = 454,
  [SMALL_STATE(41)] = 461,
  [SMALL_STATE(42)] = 468,
  [SMALL_STATE(43)] = 475,
  [SMALL_STATE(44)] = 482,
  [SMALL_STATE(45)] = 489,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_protocol_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [14] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_protocol_definition_repeat1, 2, 0, 0),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_protocol_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_protocol_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response_block, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_block, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_definition_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response_block, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 4, 0, 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_block, 4, 0, 6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response_block, 4, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 5, 0, 7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5, 0, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_protocol_definition, 4, 0, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_protocol_definition, 5, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 6, 0, 9),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 5, 0, 8),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_specifier, 3, 0, 10),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [113] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sproto(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sproto",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
